package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Caixa generated by hbm2java
 */
public class Caixa  implements java.io.Serializable {


     private int id;
     private Filial filial;
     private Pessoa pessoa;
     private String descricao;
     private String saldoInicial;
     private Set saidas = new HashSet(0);
     private Set entradas = new HashSet(0);

    public Caixa() {
    }

	
    public Caixa(int id, Filial filial, Pessoa pessoa) {
        this.id = id;
        this.filial = filial;
        this.pessoa = pessoa;
    }
    public Caixa(int id, Filial filial, Pessoa pessoa, String descricao, String saldoInicial, Set saidas, Set entradas) {
       this.id = id;
       this.filial = filial;
       this.pessoa = pessoa;
       this.descricao = descricao;
       this.saldoInicial = saldoInicial;
       this.saidas = saidas;
       this.entradas = entradas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Filial getFilial() {
        return this.filial;
    }
    
    public void setFilial(Filial filial) {
        this.filial = filial;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getSaldoInicial() {
        return this.saldoInicial;
    }
    
    public void setSaldoInicial(String saldoInicial) {
        this.saldoInicial = saldoInicial;
    }
    public Set getSaidas() {
        return this.saidas;
    }
    
    public void setSaidas(Set saidas) {
        this.saidas = saidas;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }




}


