package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int id;
     private Filial filial;
     private Pessoa pessoaByVendedorId;
     private Pessoa pessoaByClienteId;
     private Saida saida;
     private Date data;
     private Set compraItems = new HashSet(0);

    public Compra() {
    }

	
    public Compra(int id, Filial filial, Pessoa pessoaByVendedorId, Pessoa pessoaByClienteId, Saida saida) {
        this.id = id;
        this.filial = filial;
        this.pessoaByVendedorId = pessoaByVendedorId;
        this.pessoaByClienteId = pessoaByClienteId;
        this.saida = saida;
    }
    public Compra(int id, Filial filial, Pessoa pessoaByVendedorId, Pessoa pessoaByClienteId, Saida saida, Date data, Set compraItems) {
       this.id = id;
       this.filial = filial;
       this.pessoaByVendedorId = pessoaByVendedorId;
       this.pessoaByClienteId = pessoaByClienteId;
       this.saida = saida;
       this.data = data;
       this.compraItems = compraItems;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Filial getFilial() {
        return this.filial;
    }
    
    public void setFilial(Filial filial) {
        this.filial = filial;
    }
    public Pessoa getPessoaByVendedorId() {
        return this.pessoaByVendedorId;
    }
    
    public void setPessoaByVendedorId(Pessoa pessoaByVendedorId) {
        this.pessoaByVendedorId = pessoaByVendedorId;
    }
    public Pessoa getPessoaByClienteId() {
        return this.pessoaByClienteId;
    }
    
    public void setPessoaByClienteId(Pessoa pessoaByClienteId) {
        this.pessoaByClienteId = pessoaByClienteId;
    }
    public Saida getSaida() {
        return this.saida;
    }
    
    public void setSaida(Saida saida) {
        this.saida = saida;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getCompraItems() {
        return this.compraItems;
    }
    
    public void setCompraItems(Set compraItems) {
        this.compraItems = compraItems;
    }




}


