package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1



/**
 * CompraItem generated by hbm2java
 */
public class CompraItem  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Produto produto;
     private String quantidade;
     private String valorUnitario;

    public CompraItem() {
    }

	
    public CompraItem(Compra compra, Produto produto) {
        this.compra = compra;
        this.produto = produto;
    }
    public CompraItem(Compra compra, Produto produto, String quantidade, String valorUnitario) {
       this.compra = compra;
       this.produto = produto;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public String getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(String quantidade) {
        this.quantidade = quantidade;
    }
    public String getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(String valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


