package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Filial generated by hbm2java
 */
public class Filial  implements java.io.Serializable {


     private int id;
     private String nome;
     private String endereco;
     private String numero;
     private String email;
     private String telefone;
     private String flMatriz;
     private Set produtoFilials = new HashSet(0);
     private Set vendas = new HashSet(0);
     private Set systemUsers = new HashSet(0);
     private Set caixas = new HashSet(0);
     private Set compras = new HashSet(0);

    public Filial() {
    }

	
    public Filial(int id) {
        this.id = id;
    }
    public Filial(int id, String nome, String endereco, String numero, String email, String telefone, String flMatriz, Set produtoFilials, Set vendas, Set systemUsers, Set caixas, Set compras) {
       this.id = id;
       this.nome = nome;
       this.endereco = endereco;
       this.numero = numero;
       this.email = email;
       this.telefone = telefone;
       this.flMatriz = flMatriz;
       this.produtoFilials = produtoFilials;
       this.vendas = vendas;
       this.systemUsers = systemUsers;
       this.caixas = caixas;
       this.compras = compras;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getFlMatriz() {
        return this.flMatriz;
    }
    
    public void setFlMatriz(String flMatriz) {
        this.flMatriz = flMatriz;
    }
    public Set getProdutoFilials() {
        return this.produtoFilials;
    }
    
    public void setProdutoFilials(Set produtoFilials) {
        this.produtoFilials = produtoFilials;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Set getSystemUsers() {
        return this.systemUsers;
    }
    
    public void setSystemUsers(Set systemUsers) {
        this.systemUsers = systemUsers;
    }
    public Set getCaixas() {
        return this.caixas;
    }
    
    public void setCaixas(Set caixas) {
        this.caixas = caixas;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


