package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1



/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private int id;
     private String tabela;
     private String sql;

    public Log() {
    }

	
    public Log(int id) {
        this.id = id;
    }
    public Log(int id, String tabela, String sql) {
       this.id = id;
       this.tabela = tabela;
       this.sql = sql;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTabela() {
        return this.tabela;
    }
    
    public void setTabela(String tabela) {
        this.tabela = tabela;
    }
    public String getSql() {
        return this.sql;
    }
    
    public void setSql(String sql) {
        this.sql = sql;
    }




}


