package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1



/**
 * PessoaJuridica generated by hbm2java
 */
public class PessoaJuridica  implements java.io.Serializable {


     private Integer pessoaId;
     private Pessoa pessoa;
     private String cnpj;
     private String dataFundacao;
     private String nomeFantasia;

    public PessoaJuridica() {
    }

	
    public PessoaJuridica(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public PessoaJuridica(Pessoa pessoa, String cnpj, String dataFundacao, String nomeFantasia) {
       this.pessoa = pessoa;
       this.cnpj = cnpj;
       this.dataFundacao = dataFundacao;
       this.nomeFantasia = nomeFantasia;
    }
   
    public Integer getPessoaId() {
        return this.pessoaId;
    }
    
    public void setPessoaId(Integer pessoaId) {
        this.pessoaId = pessoaId;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getDataFundacao() {
        return this.dataFundacao;
    }
    
    public void setDataFundacao(String dataFundacao) {
        this.dataFundacao = dataFundacao;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }




}


