package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1



/**
 * ProdutoFilialId generated by hbm2java
 */
public class ProdutoFilialId  implements java.io.Serializable {


     private int id;
     private int produtoId;
     private int filialId;

    public ProdutoFilialId() {
    }

    public ProdutoFilialId(int id, int produtoId, int filialId) {
       this.id = id;
       this.produtoId = produtoId;
       this.filialId = filialId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getProdutoId() {
        return this.produtoId;
    }
    
    public void setProdutoId(int produtoId) {
        this.produtoId = produtoId;
    }
    public int getFilialId() {
        return this.filialId;
    }
    
    public void setFilialId(int filialId) {
        this.filialId = filialId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoFilialId) ) return false;
		 ProdutoFilialId castOther = ( ProdutoFilialId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getProdutoId()==castOther.getProdutoId())
 && (this.getFilialId()==castOther.getFilialId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getProdutoId();
         result = 37 * result + this.getFilialId();
         return result;
   }   


}


