package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int id;
     private Marca marca;
     private String descricao;
     private String precoCompra;
     private String precoVenda;
     private Set vendaItems = new HashSet(0);
     private Set produtoFilials = new HashSet(0);
     private Set compraItems = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int id, Marca marca) {
        this.id = id;
        this.marca = marca;
    }
    public Produto(int id, Marca marca, String descricao, String precoCompra, String precoVenda, Set vendaItems, Set produtoFilials, Set compraItems) {
       this.id = id;
       this.marca = marca;
       this.descricao = descricao;
       this.precoCompra = precoCompra;
       this.precoVenda = precoVenda;
       this.vendaItems = vendaItems;
       this.produtoFilials = produtoFilials;
       this.compraItems = compraItems;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getPrecoCompra() {
        return this.precoCompra;
    }
    
    public void setPrecoCompra(String precoCompra) {
        this.precoCompra = precoCompra;
    }
    public String getPrecoVenda() {
        return this.precoVenda;
    }
    
    public void setPrecoVenda(String precoVenda) {
        this.precoVenda = precoVenda;
    }
    public Set getVendaItems() {
        return this.vendaItems;
    }
    
    public void setVendaItems(Set vendaItems) {
        this.vendaItems = vendaItems;
    }
    public Set getProdutoFilials() {
        return this.produtoFilials;
    }
    
    public void setProdutoFilials(Set produtoFilials) {
        this.produtoFilials = produtoFilials;
    }
    public Set getCompraItems() {
        return this.compraItems;
    }
    
    public void setCompraItems(Set compraItems) {
        this.compraItems = compraItems;
    }




}


