package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1



/**
 * SystemGroupProgram generated by hbm2java
 */
public class SystemGroupProgram  implements java.io.Serializable {


     private int id;
     private SystemGroup systemGroup;
     private SystemProgram systemProgram;
     private String action;

    public SystemGroupProgram() {
    }

	
    public SystemGroupProgram(int id, SystemGroup systemGroup, SystemProgram systemProgram) {
        this.id = id;
        this.systemGroup = systemGroup;
        this.systemProgram = systemProgram;
    }
    public SystemGroupProgram(int id, SystemGroup systemGroup, SystemProgram systemProgram, String action) {
       this.id = id;
       this.systemGroup = systemGroup;
       this.systemProgram = systemProgram;
       this.action = action;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SystemGroup getSystemGroup() {
        return this.systemGroup;
    }
    
    public void setSystemGroup(SystemGroup systemGroup) {
        this.systemGroup = systemGroup;
    }
    public SystemProgram getSystemProgram() {
        return this.systemProgram;
    }
    
    public void setSystemProgram(SystemProgram systemProgram) {
        this.systemProgram = systemProgram;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }




}


