package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SystemGroup generated by hbm2java
 */
public class SystemGroup  implements java.io.Serializable {


     private int id;
     private String name;
     private Set systemUserGroups = new HashSet(0);
     private Set systemGroupPrograms = new HashSet(0);

    public SystemGroup() {
    }

	
    public SystemGroup(int id) {
        this.id = id;
    }
    public SystemGroup(int id, String name, Set systemUserGroups, Set systemGroupPrograms) {
       this.id = id;
       this.name = name;
       this.systemUserGroups = systemUserGroups;
       this.systemGroupPrograms = systemGroupPrograms;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getSystemUserGroups() {
        return this.systemUserGroups;
    }
    
    public void setSystemUserGroups(Set systemUserGroups) {
        this.systemUserGroups = systemUserGroups;
    }
    public Set getSystemGroupPrograms() {
        return this.systemGroupPrograms;
    }
    
    public void setSystemGroupPrograms(Set systemGroupPrograms) {
        this.systemGroupPrograms = systemGroupPrograms;
    }




}


