package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SystemUser generated by hbm2java
 */
public class SystemUser  implements java.io.Serializable {


     private int id;
     private Filial filial;
     private String name;
     private String login;
     private String password;
     private String email;
     private String frontpageId;
     private Set systemUserPrograms = new HashSet(0);
     private Set systemUserGroups = new HashSet(0);

    public SystemUser() {
    }

	
    public SystemUser(int id, Filial filial) {
        this.id = id;
        this.filial = filial;
    }
    public SystemUser(int id, Filial filial, String name, String login, String password, String email, String frontpageId, Set systemUserPrograms, Set systemUserGroups) {
       this.id = id;
       this.filial = filial;
       this.name = name;
       this.login = login;
       this.password = password;
       this.email = email;
       this.frontpageId = frontpageId;
       this.systemUserPrograms = systemUserPrograms;
       this.systemUserGroups = systemUserGroups;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Filial getFilial() {
        return this.filial;
    }
    
    public void setFilial(Filial filial) {
        this.filial = filial;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFrontpageId() {
        return this.frontpageId;
    }
    
    public void setFrontpageId(String frontpageId) {
        this.frontpageId = frontpageId;
    }
    public Set getSystemUserPrograms() {
        return this.systemUserPrograms;
    }
    
    public void setSystemUserPrograms(Set systemUserPrograms) {
        this.systemUserPrograms = systemUserPrograms;
    }
    public Set getSystemUserGroups() {
        return this.systemUserGroups;
    }
    
    public void setSystemUserGroups(Set systemUserGroups) {
        this.systemUserGroups = systemUserGroups;
    }




}


