package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1



/**
 * SystemUserGroup generated by hbm2java
 */
public class SystemUserGroup  implements java.io.Serializable {


     private int id;
     private SystemGroup systemGroup;
     private SystemUser systemUser;

    public SystemUserGroup() {
    }

    public SystemUserGroup(int id, SystemGroup systemGroup, SystemUser systemUser) {
       this.id = id;
       this.systemGroup = systemGroup;
       this.systemUser = systemUser;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SystemGroup getSystemGroup() {
        return this.systemGroup;
    }
    
    public void setSystemGroup(SystemGroup systemGroup) {
        this.systemGroup = systemGroup;
    }
    public SystemUser getSystemUser() {
        return this.systemUser;
    }
    
    public void setSystemUser(SystemUser systemUser) {
        this.systemUser = systemUser;
    }




}


