package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1



/**
 * VendaItem generated by hbm2java
 */
public class VendaItem  implements java.io.Serializable {


     private int id;
     private Produto produto;
     private Venda venda;
     private String quantidade;
     private String valorUnitario;

    public VendaItem() {
    }

	
    public VendaItem(int id, Produto produto, Venda venda) {
        this.id = id;
        this.produto = produto;
        this.venda = venda;
    }
    public VendaItem(int id, Produto produto, Venda venda, String quantidade, String valorUnitario) {
       this.id = id;
       this.produto = produto;
       this.venda = venda;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public String getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(String quantidade) {
        this.quantidade = quantidade;
    }
    public String getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(String valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


