package com.esales.model;
// Generated Nov 9, 2015 8:59:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private int id;
     private Entrada entrada;
     private Filial filial;
     private Pessoa pessoaByVendedorId;
     private Pessoa pessoaByCompradorId;
     private Date data;
     private Set vendaItems = new HashSet(0);

    public Venda() {
    }

	
    public Venda(int id, Entrada entrada, Filial filial, Pessoa pessoaByVendedorId, Pessoa pessoaByCompradorId) {
        this.id = id;
        this.entrada = entrada;
        this.filial = filial;
        this.pessoaByVendedorId = pessoaByVendedorId;
        this.pessoaByCompradorId = pessoaByCompradorId;
    }
    public Venda(int id, Entrada entrada, Filial filial, Pessoa pessoaByVendedorId, Pessoa pessoaByCompradorId, Date data, Set vendaItems) {
       this.id = id;
       this.entrada = entrada;
       this.filial = filial;
       this.pessoaByVendedorId = pessoaByVendedorId;
       this.pessoaByCompradorId = pessoaByCompradorId;
       this.data = data;
       this.vendaItems = vendaItems;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Entrada getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }
    public Filial getFilial() {
        return this.filial;
    }
    
    public void setFilial(Filial filial) {
        this.filial = filial;
    }
    public Pessoa getPessoaByVendedorId() {
        return this.pessoaByVendedorId;
    }
    
    public void setPessoaByVendedorId(Pessoa pessoaByVendedorId) {
        this.pessoaByVendedorId = pessoaByVendedorId;
    }
    public Pessoa getPessoaByCompradorId() {
        return this.pessoaByCompradorId;
    }
    
    public void setPessoaByCompradorId(Pessoa pessoaByCompradorId) {
        this.pessoaByCompradorId = pessoaByCompradorId;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getVendaItems() {
        return this.vendaItems;
    }
    
    public void setVendaItems(Set vendaItems) {
        this.vendaItems = vendaItems;
    }




}


